[custom.all.paella]
type = "local"
path = "."
ipkg = "paella.ipkg"
test = "test/test.ipkg"

[custom.all.paella-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.semantic-reflection]
type = "git"
url = "https://github.com/madman-bob/semantic-reflection"
ipkg = "semantic-reflection.ipkg"
commit = "fetch-latest:main"

